(function($){"use strict";function setNavbarFixed(win_scrolltop,menu_scrolltop){if(!$(".header").hasClass("static")){if(win_scrolltop>menu_scrolltop){$(".header_inner").addClass("fixed");if($(".header").hasClass("header5")){$(".header_inner").addClass("light_bg");}}else{$(".header_inner").removeClass("fixed");if($(".header").hasClass("header5")){$(".header_inner").removeClass("light_bg");}}}}
function resize_home_slider(){var home_slide=$("#home_slider .slide");var win_height=$(window).height();home_slide.css({height:win_height+"px"});}
if($("html").hasClass("dark-art")){resize_home_slider();$(window).on("resize",function(){resize_home_slider();});}
var $menuTop;$(window).scroll(function(){var scrollTop=$(window).scrollTop();setNavbarFixed(scrollTop,$menuTop);});if($(".parallax_item").length){$(".parallax_item").each(function(){$(this).find(".parallax_layer").parallax("center",0.4);});}
var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};var OSName="Unknown OS";if(navigator.appVersion.indexOf("Win")!=-1)OSName="Windows";else if(navigator.appVersion.indexOf("Mac")!=-1)OSName="MacOS";else if(navigator.appVersion.indexOf("X11")!=-1)OSName="UNIX";else if(navigator.appVersion.indexOf("Linux")!=-1)OSName="Linux";if(!isMobile.any()){$(".anim_element").appear();$('body').on('appear','.anim_element',function(event,$all_appeared_elements){var anim_class=$(this).attr("data-animation");var elem=$(this);var animationDelay=elem.attr("data-animation-delay");if(animationDelay!=undefined){setTimeout(function(){elem.addClass(anim_class+" animated fullOpacity");},animationDelay);}else{elem.addClass(anim_class+" animated fullOpacity");}});}
if($("#gmap_default").length){new Maplace({map_div:'#gmap_default',map_options:{set_center:[59.9335018,30.2970314],zoom:15,scrollwheel:false,controls:{panControl:true,zoomControl:true,mapTypeControl:true,scaleControl:false,streetViewControl:true,overviewMapControl:false},}}).Load();}
if($(".navbar.onepage").length){$(".navbar").onePageNav({currentClass:'active',changeHash:false,scrollSpeed:750,scrollThreshold:0.5,filter:'',easing:'swing'});}else{$("body").on("click",".navbar li a",function(){var href=$(this).attr("href");href=href.substring(1);if($("#"+href).length){$('html, body').animate({scrollTop:$("#"+href).offset().top-119},300,'linear');}else{if($(this).attr("href")!="#"){location.href=$(this).attr("href");}}});}
$("body").on("click",".navbar_search",function(){var search_box=$(".header .search_box");if(!search_box.is(":visible")){$(".logo_outer").css("opacity",0);$(".navbar_outer").css("opacity",0);search_box.slideDown(function(){search_box.find("input").val('').focus();});}
return false;});$("body").on("click",".close_search_box",function(){var search_box=$(".header .search_box");if(search_box.is(":visible")){$(".logo_outer").css("opacity",1);$(".navbar_outer").css("opacity",1);search_box.slideUp();}
return false;});$(window).scroll(function(){if($(this).scrollTop()>200){$(".scroll_to_top").fadeIn();}else{$(".scroll_to_top").fadeOut();}});$(".scroll_to_top").click(function(){$('html, body').animate({scrollTop:0},300,'linear');});$(".menu_search_btn").click(function(){if($(".menu_search").is(":visible")){$(".menu_search").fadeOut();}else{$(".menu_search").fadeIn();}
return false;});$(".close_search_btn").click(function(){$(".menu_search").fadeOut();return false;});$(".show_top_header_icon").click(function(){var icon=$(this).attr("data-icon");console.log(icon);$(".top_header_"+icon).fadeIn();});$(".close_top_header_icon").click(function(){$(this).parents(".top_header_icon_value").fadeOut();});$("body").on("click",".navbar_handle",function(){var menu=$(this).parent().find("ul.navbar");if(menu.is(":visible")){menu.fadeOut();$(".header").removeClass("rel_pos");}else{menu.fadeIn();$(".header").addClass("rel_pos");$('html, body').animate({scrollTop:$(".header").offset().top},300,'linear');}
return false;});$(window).resize(function(){var win_width=$(window).width();if(win_width>=991){$(".header").removeClass("rel_pos");$(".header .navbar").show();}});if($('.tp-banner').length){$('.tp-banner').revolution({delay:9000,startwidth:1170,startheight:600,hideThumbs:10,navigationStyle:'preview4'});}})(jQuery);